package com.example.petify.model.profile;

public enum NotificationType {
    GENERAL,
    WELCOME,
    APPOINTMENT_CREATED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REJECTED,
    NEW_APPOINTMENT_REQUEST,
    SERVICE_REMINDER,
    SYSTEM_MAINTENANCE,
    PROFILE_UPDATE,
    APPOINTMENT_REMINDER,
    PET_CHECKUP_DUE,
    SERVICE_PROVIDER_APPROVED,
    USER_BANNED,
    USER_UNBANNED
}