version: "3.8"
services:
  petify:
    build: .
    container_name: petify_backend
    env_file:
      - .env
    environment:
      DB_URL: "jdbc:mysql://db:3306/petify"
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: petify
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:
