services:
  petify:
    build: .
    container_name: petify
    env_file:
      - .env
    environment:
      DB_URL: "jdbc:mysql://db:3306/petify"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: petify
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: