package com.example.petify.domain.profile.model;

public enum NotificationType {
    GENERAL,
    WELCOME,
    APPOINTMENT_CREATED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REJECTED,
    NEW_APPOINTMENT_REQUEST,
    SERVICE_REMINDER,
    SYSTEM_MAINTENANCE,
    PROFILE_UPDATE,
    APPOINTMENT_REMINDER,
    PET_CHECKUP_DUE
}